# Generated by Django 5.1.7 on 2025-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vape_app', '0003_cliente_venta_ventaproducto_venta_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='account',
            field=models.TextField(blank=True, null=True),
        ),
    ]
