# Generated by Django 5.1.7 on 2025-04-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vape_app', '0004_cliente_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pedido',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
