# Generated by Django 5.1.7 on 2025-05-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vape_app', '0006_category_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
